package com.data_management;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;

/**
 * Reads patient data from output files generated by the HealthDataSimulator.
 * Files are expected to be in the directory specified at construction time.
 * Each line follows the format: patientId,timestamp,label,data
 */
public class FileDataReader implements DataReader {

    private final String directoryPath;

    /**
     * Creates a FileDataReader that will look for data files in the given directory.
     *
     * @param directoryPath path to the directory containing simulator output files
     */
    public FileDataReader(String directoryPath) {
        this.directoryPath = directoryPath;
    }

    /**
     * Reads all .txt and .csv files in the directory and loads each record
     * into the provided DataStorage instance.
     *
     * @param dataStorage the storage object to receive parsed records
     * @throws IOException if the directory is invalid or a file cannot be read
     */
    @Override
    public void readData(DataStorage dataStorage) throws IOException {
        File directory = new File(directoryPath);

        if (!directory.exists() || !directory.isDirectory()) {
            throw new IOException("Directory not found or is not a directory: " + directoryPath);
        }

        // Accept both .txt and .csv files
        File[] files = directory.listFiles(
                (dir, name) -> name.endsWith(".txt") || name.endsWith(".csv"));

        if (files == null || files.length == 0) {
            System.out.println("No data files found in: " + directoryPath);
            return;
        }

        for (File file : files) {
            readFile(file, dataStorage);
        }
    }

    /**
     * Reads a single file line by line, parsing each line into a patient record.
     */
    private void readFile(File file, DataStorage dataStorage) throws IOException {
        try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
            String line;
            int lineNumber = 0;

            while ((line = reader.readLine()) != null) {
                lineNumber++;
                line = line.trim();

                // Skip empty lines and comment lines
                if (line.isEmpty() || line.startsWith("#")) {
                    continue;
                }

                parseLine(line, dataStorage, file.getName(), lineNumber);
            }
        }
    }

    /**
     * Parses a single CSV line and adds the record to storage.
     * Expected format: patientId,timestamp,label,data
     *
     * Assumption: malformed lines are logged and skipped rather than
     * throwing an exception, so one bad line does not stop the whole file.
     */
    private void parseLine(String line, DataStorage dataStorage,
                           String fileName, int lineNumber) {
        String[] parts = line.split(",");

        if (parts.length != 4) {
            System.err.println("Skipping malformed line " + lineNumber
                    + " in " + fileName + ": " + line);
            return;
        }

        try {
            int patientId       = Integer.parseInt(parts[0].trim());
            long timestamp      = Long.parseLong(parts[1].trim());
            String label        = parts[2].trim();
            double measureValue = Double.parseDouble(parts[3].trim());

            dataStorage.addPatientData(patientId, measureValue, label, timestamp);

        } catch (NumberFormatException e) {
            System.err.println("Skipping line " + lineNumber + " in " + fileName
                    + " due to number format error: " + line);
        }
    }
}
